# Generated by Django 3.1.5 on 2021-01-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210111_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('cud_author', 'Can create, update and delete authors'),)},
        ),
    ]
